/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employee.service;

/**
 *
 * @author Jomax
 */
public class NewManageEmployeeForm extends javax.swing.JFrame {

    /**
     * Creates new form NewManageEmployeeForm
     */
    public NewManageEmployeeForm() {
        initComponents();
        setLocationRelativeTo(null); // This centers the window
        setTitle("Manage Employee - FinMark Payroll System");
        setSize(800, 620);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageEmployeeDetailslabel = new javax.swing.JLabel();
        BirthdayLabel = new javax.swing.JLabel();
        EmployeeNumberLabel1 = new javax.swing.JLabel();
        LastNameLabel1 = new javax.swing.JLabel();
        FirstNameLabel1 = new javax.swing.JLabel();
        PhilHealthLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        PhoneNumberLabel = new javax.swing.JLabel();
        SSSLabel = new javax.swing.JLabel();
        PositionLabel = new javax.swing.JLabel();
        StatusLabel = new javax.swing.JLabel();
        PhoneAllowanceLabel = new javax.swing.JLabel();
        ImmediateSupervisorLabel = new javax.swing.JLabel();
        BasicSalaryLabel = new javax.swing.JLabel();
        RiceSubsidyLabel = new javax.swing.JLabel();
        HourlyRateLabel = new javax.swing.JLabel();
        ClothingAllowanceLabel = new javax.swing.JLabel();
        GrossSemimonthlyLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressField = new javax.swing.JTextArea();
        StatusComboBox = new javax.swing.JComboBox<>();
        lastNameField = new javax.swing.JTextField();
        employeeNumberField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        firstNameField = new javax.swing.JTextField();
        birthdayField = new javax.swing.JTextField();
        philhealthField = new javax.swing.JTextField();
        positionField = new javax.swing.JTextField();
        pagibigField = new javax.swing.JTextField();
        basicSalaryField = new javax.swing.JTextField();
        grossRateField = new javax.swing.JTextField();
        phoneAllowanceField = new javax.swing.JTextField();
        lastNameField5 = new javax.swing.JTextField();
        tinField = new javax.swing.JTextField();
        sssField = new javax.swing.JTextField();
        lastNameField7 = new javax.swing.JTextField();
        riceSubsidyField = new javax.swing.JTextField();
        supervisorField = new javax.swing.JTextField();
        lastNameField9 = new javax.swing.JTextField();
        hourlyRateField = new javax.swing.JTextField();
        clothingAllowanceField = new javax.swing.JTextField();
        lastNameField11 = new javax.swing.JTextField();
        PagibigLabel1 = new javax.swing.JLabel();
        TINLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Employee");
        setPreferredSize(new java.awt.Dimension(800, 620));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageEmployeeDetailslabel.setFont(new java.awt.Font("Impact", 1, 26)); // NOI18N
        ManageEmployeeDetailslabel.setForeground(new java.awt.Color(59, 115, 185));
        ManageEmployeeDetailslabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ManageEmployeeDetailslabel.setText("Manage Employee Details");
        getContentPane().add(ManageEmployeeDetailslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 300, 40));

        BirthdayLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BirthdayLabel.setText("Birthday");
        getContentPane().add(BirthdayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 160, -1));

        EmployeeNumberLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmployeeNumberLabel1.setText("Employee #");
        getContentPane().add(EmployeeNumberLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 160, -1));

        LastNameLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LastNameLabel1.setText("Last Name\t");
        getContentPane().add(LastNameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 160, -1));

        FirstNameLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FirstNameLabel1.setText("First Name");
        getContentPane().add(FirstNameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 160, -1));

        PhilHealthLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PhilHealthLabel.setText("PhilHealth #");
        getContentPane().add(PhilHealthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 160, -1));

        AddressLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddressLabel.setText("Address");
        getContentPane().add(AddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 160, -1));

        PhoneNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PhoneNumberLabel.setText("Phone Number");
        getContentPane().add(PhoneNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 160, -1));

        SSSLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SSSLabel.setText("SSS #");
        getContentPane().add(SSSLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 160, -1));

        PositionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PositionLabel.setText("Position");
        getContentPane().add(PositionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 160, -1));

        StatusLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StatusLabel.setText("Status");
        getContentPane().add(StatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 160, -1));

        PhoneAllowanceLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PhoneAllowanceLabel.setText("Phone Allowance");
        getContentPane().add(PhoneAllowanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 160, -1));

        ImmediateSupervisorLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ImmediateSupervisorLabel.setText("Immediate Supervisor");
        getContentPane().add(ImmediateSupervisorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 160, -1));

        BasicSalaryLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BasicSalaryLabel.setText("Basic Salary");
        getContentPane().add(BasicSalaryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 160, -1));

        RiceSubsidyLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RiceSubsidyLabel.setText("Rice Subsidy");
        getContentPane().add(RiceSubsidyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 160, -1));

        HourlyRateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HourlyRateLabel.setText("Hourly Rate");
        getContentPane().add(HourlyRateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 160, -1));

        ClothingAllowanceLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ClothingAllowanceLabel.setText("Clothing Allowance");
        getContentPane().add(ClothingAllowanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 160, -1));

        GrossSemimonthlyLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GrossSemimonthlyLabel.setText("Gross Semi-monthly");
        getContentPane().add(GrossSemimonthlyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 160, -1));

        addressField.setColumns(20);
        addressField.setRows(5);
        addressField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane1.setViewportView(addressField);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 180, 50));

        StatusComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Probationary" }));
        StatusComboBox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        StatusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(StatusComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 180, 30));

        lastNameField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(lastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 180, -1));

        employeeNumberField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        employeeNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeNumberFieldActionPerformed(evt);
            }
        });
        getContentPane().add(employeeNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 180, -1));

        phoneField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        phoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFieldActionPerformed(evt);
            }
        });
        getContentPane().add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 180, -1));

        firstNameField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 180, -1));

        birthdayField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        birthdayField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdayFieldActionPerformed(evt);
            }
        });
        getContentPane().add(birthdayField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 180, -1));

        philhealthField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        philhealthField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                philhealthFieldActionPerformed(evt);
            }
        });
        getContentPane().add(philhealthField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 180, -1));

        positionField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        positionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionFieldActionPerformed(evt);
            }
        });
        getContentPane().add(positionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 180, -1));

        pagibigField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pagibigField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagibigFieldActionPerformed(evt);
            }
        });
        getContentPane().add(pagibigField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 180, -1));

        basicSalaryField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        basicSalaryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicSalaryFieldActionPerformed(evt);
            }
        });
        getContentPane().add(basicSalaryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 180, -1));

        grossRateField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        grossRateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grossRateFieldActionPerformed(evt);
            }
        });
        getContentPane().add(grossRateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 180, -1));

        phoneAllowanceField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        phoneAllowanceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneAllowanceFieldActionPerformed(evt);
            }
        });
        getContentPane().add(phoneAllowanceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 180, -1));

        lastNameField5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lastNameField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameField5ActionPerformed(evt);
            }
        });
        getContentPane().add(lastNameField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 180, -1));

        tinField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tinField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinFieldActionPerformed(evt);
            }
        });
        getContentPane().add(tinField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 180, -1));

        sssField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        sssField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sssFieldActionPerformed(evt);
            }
        });
        getContentPane().add(sssField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 180, -1));

        lastNameField7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lastNameField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameField7ActionPerformed(evt);
            }
        });
        getContentPane().add(lastNameField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 180, -1));

        riceSubsidyField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        riceSubsidyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riceSubsidyFieldActionPerformed(evt);
            }
        });
        getContentPane().add(riceSubsidyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 180, -1));

        supervisorField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        supervisorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supervisorFieldActionPerformed(evt);
            }
        });
        getContentPane().add(supervisorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 180, -1));

        lastNameField9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lastNameField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameField9ActionPerformed(evt);
            }
        });
        getContentPane().add(lastNameField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 180, -1));

        hourlyRateField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        hourlyRateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourlyRateFieldActionPerformed(evt);
            }
        });
        getContentPane().add(hourlyRateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 180, -1));

        clothingAllowanceField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        clothingAllowanceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clothingAllowanceFieldActionPerformed(evt);
            }
        });
        getContentPane().add(clothingAllowanceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 180, -1));

        lastNameField11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lastNameField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameField11ActionPerformed(evt);
            }
        });
        getContentPane().add(lastNameField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 180, -1));

        PagibigLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PagibigLabel1.setText("Pag-ibig #");
        getContentPane().add(PagibigLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 160, -1));

        TINLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TINLabel.setText("TIN #");
        getContentPane().add(TINLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 160, -1));

        jButton1.setBackground(new java.awt.Color(128, 128, 128));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancel");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, 100, -1));

        SaveButton.setBackground(new java.awt.Color(59, 115, 185));
        SaveButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveButton.setText("Save");
        SaveButton.setToolTipText("");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 100, -1));

        DeleteButton.setBackground(new java.awt.Color(255, 0, 0));
        DeleteButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton.setText("Delete");
        getContentPane().add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 100, -1));

        UpdateButton.setBackground(new java.awt.Color(0, 100, 0));
        UpdateButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateButton.setText("Update");
        getContentPane().add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StatusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusComboBoxActionPerformed

    private void lastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldActionPerformed

    private void employeeNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeNumberFieldActionPerformed

    private void phoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFieldActionPerformed

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void birthdayFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdayFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdayFieldActionPerformed

    private void philhealthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_philhealthFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_philhealthFieldActionPerformed

    private void positionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionFieldActionPerformed

    private void pagibigFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagibigFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagibigFieldActionPerformed

    private void basicSalaryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicSalaryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basicSalaryFieldActionPerformed

    private void grossRateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grossRateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grossRateFieldActionPerformed

    private void phoneAllowanceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneAllowanceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneAllowanceFieldActionPerformed

    private void lastNameField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameField5ActionPerformed

    private void tinFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinFieldActionPerformed

    private void sssFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sssFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sssFieldActionPerformed

    private void lastNameField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameField7ActionPerformed

    private void riceSubsidyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riceSubsidyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_riceSubsidyFieldActionPerformed

    private void supervisorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supervisorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supervisorFieldActionPerformed

    private void lastNameField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameField9ActionPerformed

    private void hourlyRateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourlyRateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hourlyRateFieldActionPerformed

    private void clothingAllowanceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clothingAllowanceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clothingAllowanceFieldActionPerformed

    private void lastNameField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameField11ActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewManageEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewManageEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewManageEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewManageEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewManageEmployeeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JLabel BasicSalaryLabel;
    private javax.swing.JLabel BirthdayLabel;
    private javax.swing.JLabel ClothingAllowanceLabel;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel EmployeeNumberLabel1;
    private javax.swing.JLabel FirstNameLabel1;
    private javax.swing.JLabel GrossSemimonthlyLabel;
    private javax.swing.JLabel HourlyRateLabel;
    private javax.swing.JLabel ImmediateSupervisorLabel;
    private javax.swing.JLabel LastNameLabel1;
    private javax.swing.JLabel ManageEmployeeDetailslabel;
    private javax.swing.JLabel PagibigLabel1;
    private javax.swing.JLabel PhilHealthLabel;
    private javax.swing.JLabel PhoneAllowanceLabel;
    private javax.swing.JLabel PhoneNumberLabel;
    private javax.swing.JLabel PositionLabel;
    private javax.swing.JLabel RiceSubsidyLabel;
    private javax.swing.JLabel SSSLabel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JComboBox<String> StatusComboBox;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JLabel TINLabel;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JTextArea addressField;
    private javax.swing.JTextField basicSalaryField;
    private javax.swing.JTextField birthdayField;
    private javax.swing.JTextField clothingAllowanceField;
    private javax.swing.JTextField employeeNumberField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JTextField grossRateField;
    private javax.swing.JTextField hourlyRateField;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JTextField lastNameField11;
    private javax.swing.JTextField lastNameField5;
    private javax.swing.JTextField lastNameField7;
    private javax.swing.JTextField lastNameField9;
    private javax.swing.JTextField pagibigField;
    private javax.swing.JTextField philhealthField;
    private javax.swing.JTextField phoneAllowanceField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JTextField positionField;
    private javax.swing.JTextField riceSubsidyField;
    private javax.swing.JTextField sssField;
    private javax.swing.JTextField supervisorField;
    private javax.swing.JTextField tinField;
    // End of variables declaration//GEN-END:variables
}
