/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import accounting.view.ApproveFinalReports;
import accounting.view.AuditTrailView;
import accounting.view.ViewPayrollReports;
import auth.service.NewLoginUI;
import java.io.File;
import javax.swing.JOptionPane;
import utils.JWTUtil;
import utils.SessionManager;

/**
 *
 * @author Jomax
 */
public class AccountingHeadDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AccountingHeadDashboard
     */
    private javax.swing.Timer tokenMonitor;
    
    public AccountingHeadDashboard() {
        initComponents();
        setLocationRelativeTo(null); // This centers the window
        setTitle("Accounting Head Dashboard - FinMark Payroll System");
        setSize(800, 500);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);
        startTokenMonitor(); // Start the token watcher
    }
    
    // ✅ This method checks token expiration every minute
private void startTokenMonitor() {
    tokenMonitor = new javax.swing.Timer(60000, e -> {
        String token = SessionManager.getToken();
        if (token == null || !JWTUtil.validateToken(token)) {
            JOptionPane.showMessageDialog(this, "Your session has expired. Please log in again.");
            SessionManager.logout();
            dispose(); // Close dashboard
            new NewLoginUI().setVisible(true); // Return to login
        }
    });
    tokenMonitor.start();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AccountingHeadDashboard = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();
        AuditTrailButton = new javax.swing.JButton();
        ViewPayrollReportsButton = new javax.swing.JButton();
        ApproveFinalReportsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AccountingHeadDashboard");
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 102));
        jPanel1.setToolTipText("");
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AccountingHeadDashboard.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        AccountingHeadDashboard.setForeground(new java.awt.Color(255, 255, 255));
        AccountingHeadDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccountingHeadDashboard.setText("Accounting Head Dashboard");
        AccountingHeadDashboard.setToolTipText("Accounting Head Dashboard");
        AccountingHeadDashboard.setMaximumSize(new java.awt.Dimension(500, 40));
        AccountingHeadDashboard.setMinimumSize(new java.awt.Dimension(500, 40));
        AccountingHeadDashboard.setPreferredSize(new java.awt.Dimension(500, 40));
        jPanel1.add(AccountingHeadDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 500, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 80));

        LogoutButton.setBackground(new java.awt.Color(255, 0, 0));
        LogoutButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logout.png"))); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.setToolTipText("Logout");
        LogoutButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogoutButton.setMaximumSize(new java.awt.Dimension(200, 40));
        LogoutButton.setMinimumSize(new java.awt.Dimension(200, 40));
        LogoutButton.setPreferredSize(new java.awt.Dimension(200, 40));
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 200, 40));

        AuditTrailButton.setBackground(new java.awt.Color(0, 128, 128));
        AuditTrailButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        AuditTrailButton.setForeground(new java.awt.Color(255, 255, 255));
        AuditTrailButton.setText("Audit Trail");
        AuditTrailButton.setToolTipText("Audit Trail");
        AuditTrailButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AuditTrailButton.setMaximumSize(new java.awt.Dimension(200, 40));
        AuditTrailButton.setMinimumSize(new java.awt.Dimension(200, 40));
        AuditTrailButton.setPreferredSize(new java.awt.Dimension(400, 40));
        AuditTrailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuditTrailButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AuditTrailButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 200, 40));

        ViewPayrollReportsButton.setBackground(new java.awt.Color(0, 153, 76));
        ViewPayrollReportsButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        ViewPayrollReportsButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewPayrollReportsButton.setText("View Payroll Reports");
        ViewPayrollReportsButton.setToolTipText("View Payroll Reports");
        ViewPayrollReportsButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ViewPayrollReportsButton.setMaximumSize(new java.awt.Dimension(200, 40));
        ViewPayrollReportsButton.setMinimumSize(new java.awt.Dimension(200, 40));
        ViewPayrollReportsButton.setPreferredSize(new java.awt.Dimension(200, 40));
        ViewPayrollReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPayrollReportsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ViewPayrollReportsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 200, 40));

        ApproveFinalReportsButton.setBackground(new java.awt.Color(255, 153, 0));
        ApproveFinalReportsButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        ApproveFinalReportsButton.setForeground(new java.awt.Color(255, 255, 255));
        ApproveFinalReportsButton.setText("Approve Final Reports");
        ApproveFinalReportsButton.setToolTipText("Approve Final Reports");
        ApproveFinalReportsButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ApproveFinalReportsButton.setMaximumSize(new java.awt.Dimension(200, 40));
        ApproveFinalReportsButton.setMinimumSize(new java.awt.Dimension(200, 40));
        ApproveFinalReportsButton.setPreferredSize(new java.awt.Dimension(200, 40));
        ApproveFinalReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApproveFinalReportsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ApproveFinalReportsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 200, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AuditTrailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuditTrailButtonActionPerformed
    new AuditTrailView().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_AuditTrailButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
    // Show confirmation dialog to the user
    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        // Clear stored session information (username, role, token)
        SessionManager.logout();

        // Delete the saved token file if it exists
        File tokenFile = new File("remember_token.dat");
        if (tokenFile.exists()) {
            tokenFile.delete(); // Remove saved JWT token used by 'Remember Me'
        }

        // Close the current dashboard window
        this.dispose();

        // Open the login screen again
        new NewLoginUI().setVisible(true);
    }
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void ViewPayrollReportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPayrollReportsButtonActionPerformed
    new ViewPayrollReports().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_ViewPayrollReportsButtonActionPerformed

    private void ApproveFinalReportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApproveFinalReportsButtonActionPerformed
    new ApproveFinalReports().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_ApproveFinalReportsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountingHeadDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountingHeadDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountingHeadDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountingHeadDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountingHeadDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountingHeadDashboard;
    private javax.swing.JButton ApproveFinalReportsButton;
    private javax.swing.JButton AuditTrailButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton ViewPayrollReportsButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
