/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import admin.view.UnlockUserForm;
import admin.view.ViewAllUsersForm;
import admin.view.ViewLockedUsersForm;
import admin.view.ViewSystemLogsForm;
import auth.service.LoginController;
import auth.service.LoginUI;
import java.io.File;
import javax.swing.JOptionPane;
import utils.JWTUtil;
import utils.SessionManager;

/**
 *
 * @author Jomax
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
  private javax.swing.Timer tokenMonitor;  
    
    public AdminDashboard() {
        initComponents();
        setLocationRelativeTo(null); // This centers the window
        setTitle("Admin Dashboard - FinMark Payroll System");
        setSize(750, 500);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);
        startTokenMonitor(); // Start the token watcher
    }
    
    // This method checks token expiration every 10 minutes
private void startTokenMonitor() {
    // Timer set to run every 10 minutes (600,000 milliseconds)
    // This code inside will execute once every 10 minutes
    tokenMonitor = new javax.swing.Timer(600000, e -> { 
        String token = SessionManager.getToken();
        if (token == null || !JWTUtil.validateToken(token)) {
            JOptionPane.showMessageDialog(this, "Your session has expired. Please log in again.");
            SessionManager.logout();
            dispose(); // Close dashboard
            new LoginUI().setVisible(true); // Return to login
        }
    });
    tokenMonitor.start();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AdminDashboardLabel = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();
        ViewLockedUsersButton = new javax.swing.JButton();
        ViewAllUsersButton = new javax.swing.JButton();
        UnlockUserButton = new javax.swing.JButton();
        ViewSystemLogsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Dashboard");
        setMinimumSize(new java.awt.Dimension(750, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 128, 128));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminDashboardLabel.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        AdminDashboardLabel.setForeground(new java.awt.Color(255, 255, 255));
        AdminDashboardLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminDashboardLabel.setText("Admin Dashboard");
        AdminDashboardLabel.setMaximumSize(new java.awt.Dimension(400, 40));
        AdminDashboardLabel.setMinimumSize(new java.awt.Dimension(400, 40));
        AdminDashboardLabel.setPreferredSize(new java.awt.Dimension(400, 40));
        jPanel1.add(AdminDashboardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 400, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 80));

        LogoutButton.setBackground(new java.awt.Color(244, 67, 54));
        LogoutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logout.png"))); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.setToolTipText("Logout");
        LogoutButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogoutButton.setMaximumSize(new java.awt.Dimension(240, 40));
        LogoutButton.setMinimumSize(new java.awt.Dimension(240, 40));
        LogoutButton.setPreferredSize(new java.awt.Dimension(240, 40));
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 240, 40));

        ViewLockedUsersButton.setBackground(new java.awt.Color(0, 123, 255));
        ViewLockedUsersButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewLockedUsersButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewLockedUsersButton.setText("View Locked Users");
        ViewLockedUsersButton.setToolTipText("View Locked Users");
        ViewLockedUsersButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ViewLockedUsersButton.setMaximumSize(new java.awt.Dimension(240, 40));
        ViewLockedUsersButton.setMinimumSize(new java.awt.Dimension(240, 40));
        ViewLockedUsersButton.setPreferredSize(new java.awt.Dimension(240, 40));
        ViewLockedUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewLockedUsersButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ViewLockedUsersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 240, 40));

        ViewAllUsersButton.setBackground(new java.awt.Color(0, 200, 83));
        ViewAllUsersButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewAllUsersButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewAllUsersButton.setText("View All Users");
        ViewAllUsersButton.setToolTipText("View All Users");
        ViewAllUsersButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ViewAllUsersButton.setMaximumSize(new java.awt.Dimension(240, 40));
        ViewAllUsersButton.setMinimumSize(new java.awt.Dimension(240, 40));
        ViewAllUsersButton.setPreferredSize(new java.awt.Dimension(240, 40));
        ViewAllUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAllUsersButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ViewAllUsersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 240, 40));

        UnlockUserButton.setBackground(new java.awt.Color(255, 87, 34));
        UnlockUserButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UnlockUserButton.setForeground(new java.awt.Color(255, 255, 255));
        UnlockUserButton.setText("Unlock User");
        UnlockUserButton.setToolTipText("Unlock User");
        UnlockUserButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UnlockUserButton.setMaximumSize(new java.awt.Dimension(240, 40));
        UnlockUserButton.setMinimumSize(new java.awt.Dimension(240, 40));
        UnlockUserButton.setPreferredSize(new java.awt.Dimension(240, 40));
        UnlockUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnlockUserButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UnlockUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 240, 40));

        ViewSystemLogsButton.setBackground(new java.awt.Color(255, 193, 7));
        ViewSystemLogsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewSystemLogsButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewSystemLogsButton.setText("View System Logs");
        ViewSystemLogsButton.setToolTipText("View System Logs");
        ViewSystemLogsButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ViewSystemLogsButton.setMaximumSize(new java.awt.Dimension(240, 40));
        ViewSystemLogsButton.setMinimumSize(new java.awt.Dimension(240, 40));
        ViewSystemLogsButton.setPreferredSize(new java.awt.Dimension(240, 40));
        ViewSystemLogsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewSystemLogsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ViewSystemLogsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 240, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
  // Ask the user to confirm logout
    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        // ✅ 1. Get the currently logged-in username
        String username = SessionManager.getUsername();

        // ✅ 2. Clear the session in the database (prevent multi-login)
        LoginController.clearSession(username);

        // ✅ 3. Clear session in memory (username, role, token)
        SessionManager.logout();
        
        // ✅ 4. Delete token in the database (so user won't be auto-logged in again)
        utils.RememberTokenUtil.deleteToken(username);

        // ✅ 5. Delete the saved token file (Remember Me feature)
        File tokenFile = new File("remember_token.dat");
        if (tokenFile.exists()) {
            tokenFile.delete();
        }

        // ✅ 6. Close current window (this dashboard)
        this.dispose();

        // ✅ 7. Show login screen again
        new LoginUI().setVisible(true);
    }
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void ViewLockedUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewLockedUsersButtonActionPerformed
    this.dispose();
    new ViewLockedUsersForm().setVisible(true);
    }//GEN-LAST:event_ViewLockedUsersButtonActionPerformed

    private void ViewAllUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAllUsersButtonActionPerformed
    this.dispose();
    new ViewAllUsersForm().setVisible(true);
    }//GEN-LAST:event_ViewAllUsersButtonActionPerformed

    private void UnlockUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnlockUserButtonActionPerformed
    this.dispose();
    new UnlockUserForm().setVisible(true);
    }//GEN-LAST:event_UnlockUserButtonActionPerformed

    private void ViewSystemLogsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewSystemLogsButtonActionPerformed
    this.dispose(); // close the page
    new ViewSystemLogsForm().setVisible(true); // go back to Admin Dashboard page
    }//GEN-LAST:event_ViewSystemLogsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminDashboardLabel;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton UnlockUserButton;
    private javax.swing.JButton ViewAllUsersButton;
    private javax.swing.JButton ViewLockedUsersButton;
    private javax.swing.JButton ViewSystemLogsButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
