/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import auth.service.NewLoginUI;
import employee.view.EmployeePayslipView;
import employee.view.EmployeeAttendanceView;
import employee.view.EmployeeLeaveRequestsView;
import java.io.File;
import javax.swing.JOptionPane;
import utils.JWTUtil;
import utils.SessionManager;

/**
 *
 * @author Jomax
 */
public class EmployeeDashboard extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeDashboard
     */
    private javax.swing.Timer tokenMonitor;
    
    public EmployeeDashboard() {
        initComponents();
        setLocationRelativeTo(null); // This centers the window
        setTitle("Employee Dashboard - FinMark Payroll System");
        setSize(600, 450);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);
        startTokenMonitor(); // Start the token watcher
    }
    
    // ✅ This method checks token expiration every minute
private void startTokenMonitor() {
    tokenMonitor = new javax.swing.Timer(60000, e -> {
        String token = SessionManager.getToken();
        if (token == null || !JWTUtil.validateToken(token)) {
            JOptionPane.showMessageDialog(this, "Your session has expired. Please log in again.");
            SessionManager.logout();
            dispose(); // Close dashboard
            new NewLoginUI().setVisible(true); // Return to login
        }
    });
    tokenMonitor.start();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        WelcomeLabel = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();
        ViewPayslipButton = new javax.swing.JButton();
        ViewLeaveRequestsButton = new javax.swing.JButton();
        ViewAttendanceButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Dashboard");
        setMinimumSize(new java.awt.Dimension(600, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(70, 130, 180));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeLabel.setText("Welcome, [Employee Name]");
        WelcomeLabel.setMaximumSize(new java.awt.Dimension(300, 30));
        WelcomeLabel.setMinimumSize(new java.awt.Dimension(300, 30));
        WelcomeLabel.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel1.add(WelcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 300, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 80));

        LogoutButton.setBackground(new java.awt.Color(192, 57, 43));
        LogoutButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logout.png"))); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.setToolTipText("Logout");
        LogoutButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogoutButton.setMaximumSize(new java.awt.Dimension(240, 35));
        LogoutButton.setMinimumSize(new java.awt.Dimension(240, 35));
        LogoutButton.setPreferredSize(new java.awt.Dimension(240, 35));
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 240, 35));

        ViewPayslipButton.setBackground(new java.awt.Color(0, 128, 255));
        ViewPayslipButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        ViewPayslipButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewPayslipButton.setText("View Payslip");
        ViewPayslipButton.setToolTipText("View Payslip");
        ViewPayslipButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ViewPayslipButton.setMaximumSize(new java.awt.Dimension(240, 35));
        ViewPayslipButton.setMinimumSize(new java.awt.Dimension(240, 35));
        ViewPayslipButton.setPreferredSize(new java.awt.Dimension(240, 35));
        ViewPayslipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPayslipButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ViewPayslipButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 240, 35));

        ViewLeaveRequestsButton.setBackground(new java.awt.Color(0, 153, 76));
        ViewLeaveRequestsButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        ViewLeaveRequestsButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewLeaveRequestsButton.setText("View Leave Requests");
        ViewLeaveRequestsButton.setToolTipText("View Leave Requests");
        ViewLeaveRequestsButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ViewLeaveRequestsButton.setMaximumSize(new java.awt.Dimension(240, 35));
        ViewLeaveRequestsButton.setMinimumSize(new java.awt.Dimension(240, 35));
        ViewLeaveRequestsButton.setPreferredSize(new java.awt.Dimension(240, 35));
        ViewLeaveRequestsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewLeaveRequestsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ViewLeaveRequestsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 240, 35));

        ViewAttendanceButton.setBackground(new java.awt.Color(255, 153, 0));
        ViewAttendanceButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        ViewAttendanceButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewAttendanceButton.setText("View Attendance");
        ViewAttendanceButton.setToolTipText("View Attendance");
        ViewAttendanceButton.setMaximumSize(new java.awt.Dimension(240, 35));
        ViewAttendanceButton.setMinimumSize(new java.awt.Dimension(240, 35));
        ViewAttendanceButton.setPreferredSize(new java.awt.Dimension(240, 35));
        ViewAttendanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAttendanceButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ViewAttendanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 240, 35));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
    // Show confirmation dialog to the user
    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        // Clear stored session information (username, role, token)
        SessionManager.logout();

        // Delete the saved token file if it exists
        File tokenFile = new File("remember_token.dat");
        if (tokenFile.exists()) {
            tokenFile.delete(); // Remove saved JWT token used by 'Remember Me'
        }

        // Close the current dashboard window
        this.dispose();

        // Open the login screen again
        new NewLoginUI().setVisible(true);
    }
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void ViewPayslipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPayslipButtonActionPerformed
    new EmployeePayslipView().setVisible(true);
    this.dispose();        
    }//GEN-LAST:event_ViewPayslipButtonActionPerformed

    private void ViewLeaveRequestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewLeaveRequestsButtonActionPerformed
    new EmployeeLeaveRequestsView().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_ViewLeaveRequestsButtonActionPerformed

    private void ViewAttendanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAttendanceButtonActionPerformed
 new EmployeeAttendanceView().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_ViewAttendanceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton ViewAttendanceButton;
    private javax.swing.JButton ViewLeaveRequestsButton;
    private javax.swing.JButton ViewPayslipButton;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
