/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import utils.SessionManager;
import auth.service.JWTUtil;
import employee.service.ManageEmployeeForm;
import auth.service.LoginController;
import auth.service.NewLoginUI;
import javax.swing.JOptionPane;
import javax.swing.*;



/**
 *
 * @author Jomax
 */
public class HRDashboard extends javax.swing.JFrame {

    /**
     * Creates new form HRDashboard
     */
    public HRDashboard() {
        initComponents();
        setLocationRelativeTo(null);
    
String role = SessionManager.getRole();

// Disable HR buttons if the user is not HR Personnel
if (!"HR Personnel".equalsIgnoreCase(role)) {
    manageEmployeesButton.setEnabled(false);
    viewEmployeeListButton1.setEnabled(false);
    ViewLeaveRequestsButton.setEnabled(false);
}

// Disable leave access if the user is not a Team Leader
if (!"Team Leader".equalsIgnoreCase(role)) {
    ViewLeaveRequestsButton.setEnabled(false); // I'll use this later to limit access to their own team
}

// Hide salary-related actions if not Payroll Manager
if (!"Payroll Manager".equalsIgnoreCase(role)) {
    ViewMySalaryPayslipButton.setEnabled(false); // This button is mainly for payroll-related roles
}

// Temporarily disable reports (for Accounting Head only)
if (!"Accounting Head".equalsIgnoreCase(role)) {
    // viewReportsButton.setEnabled(false); // I'll enable this once I add the reports module
}

// Block employee-only actions for non-Regular Employees
if (!"Regular Employee".equalsIgnoreCase(role)) {
    // I'll put restrictions here if needed later for regular users
}

        
    // Custom session check logic
    String token = SessionManager.getToken(); // make sure to use full path or import it

    if (token == null || !JWTUtil.validateToken(token)) {
        JOptionPane.showMessageDialog(this, "Invalid or expired session. Please login again.");
        this.dispose();
        new NewLoginUI().setVisible(true);
    } else {
        System.out.println("Access granted to: " + SessionManager.getUsername());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();
        ViewLeaveRequestsButton = new javax.swing.JButton();
        manageEmployeesButton = new javax.swing.JButton();
        viewEmployeeListButton1 = new javax.swing.JButton();
        ViewMySalaryPayslipButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(850, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 100));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        jLabel1.setText("HR Personnel Dashboard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1480, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2040, -1));

        LogoutButton.setBackground(new java.awt.Color(0, 172, 238));
        LogoutButton.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 210, -1));

        ViewLeaveRequestsButton.setBackground(new java.awt.Color(0, 172, 238));
        ViewLeaveRequestsButton.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ViewLeaveRequestsButton.setText("View Leave Requests");
        ViewLeaveRequestsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewLeaveRequestsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ViewLeaveRequestsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 210, -1));

        manageEmployeesButton.setBackground(new java.awt.Color(0, 172, 238));
        manageEmployeesButton.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        manageEmployeesButton.setText("Manage Employees");
        manageEmployeesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(manageEmployeesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 210, -1));

        viewEmployeeListButton1.setBackground(new java.awt.Color(0, 172, 238));
        viewEmployeeListButton1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        viewEmployeeListButton1.setText("View Employee List");
        viewEmployeeListButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmployeeListButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(viewEmployeeListButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 210, -1));

        ViewMySalaryPayslipButton.setBackground(new java.awt.Color(0, 172, 238));
        ViewMySalaryPayslipButton.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ViewMySalaryPayslipButton.setText("View My Salary Payslip");
        ViewMySalaryPayslipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewMySalaryPayslipButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ViewMySalaryPayslipButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);
if (confirm == JOptionPane.YES_OPTION) {
    this.dispose();
    new NewLoginUI().setVisible(true); // bumalik sa login form
}

    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void ViewLeaveRequestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewLeaveRequestsButtonActionPerformed
    String employeeId = SessionManager.getUsername(); // or a specific ID
    String result = leave.service.LeaveService.viewLeaveRequests(employeeId);
    JOptionPane.showMessageDialog(this, result);
    }//GEN-LAST:event_ViewLeaveRequestsButtonActionPerformed

    private void manageEmployeesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeesButtonActionPerformed
    new ManageEmployeeForm().setVisible(true);
    this.dispose(); // or this.setVisible(false);
    }//GEN-LAST:event_manageEmployeesButtonActionPerformed

    private void viewEmployeeListButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmployeeListButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewEmployeeListButton1ActionPerformed

    private void ViewMySalaryPayslipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMySalaryPayslipButtonActionPerformed
    String employeeId = SessionManager.getUsername(); // or hardcoded "EMP001"
    String result = payroll.service.PayrollService.calculateSalary(employeeId);

    javax.swing.JOptionPane.showMessageDialog(this, result);
    }//GEN-LAST:event_ViewMySalaryPayslipButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HRDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HRDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HRDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HRDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HRDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton ViewLeaveRequestsButton;
    private javax.swing.JButton ViewMySalaryPayslipButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manageEmployeesButton;
    private javax.swing.JButton viewEmployeeListButton1;
    // End of variables declaration//GEN-END:variables
}
