/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import auth.service.LoginController;
import auth.service.LoginUI;
import hr.view.HRPayslipView;
import hr.view.EmployeeListForm;
import hr.view.ManageEmployeeForm;
import java.io.File;
import leave.service.NewLeaveRequest;
import utils.JWTUtil;
import utils.SessionManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Jomax
 */
public class HRDashboard extends javax.swing.JFrame {

    /**
     * Creates new form HRDashboard
     */
 private javax.swing.Timer tokenMonitor;   
    
    public HRDashboard() {
        initComponents();
        setTitle("HR Dashboard - FinMark Payroll System");
        setSize(550, 520);
        setLocationRelativeTo(null); // This centers the window
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);
        startTokenMonitor(); // Start the token watcher
    }

    // ONE MAIN METHOD ONLY
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new HRDashboard().setVisible(true);
        });
    }
    
    //  This method checks token expiration every 10 minutes
private void startTokenMonitor() {
    // Timer set to run every 10 minutes (600,000 milliseconds)
    // This code inside will execute once every 10 minutes
    tokenMonitor = new javax.swing.Timer(600000, e -> {
        String token = SessionManager.getToken();
        if (token == null || !JWTUtil.validateToken(token)) {
            JOptionPane.showMessageDialog(this, "Your session has expired. Please log in again.");
            SessionManager.logout();
            dispose(); // Close dashboard
            new LoginUI().setVisible(true); // Return to login
        }
    });
    tokenMonitor.start();
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HRlabel = new javax.swing.JLabel();
        Dashboardlabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        viewEmployeesButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        manageEmployeesButton = new javax.swing.JButton();
        leaveRequestsButton1 = new javax.swing.JButton();
        payslipButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 520));
        setPreferredSize(new java.awt.Dimension(550, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(59, 115, 185));
        jPanel1.setMinimumSize(new java.awt.Dimension(150, 1000));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HRlabel.setFont(new java.awt.Font("Impact", 1, 40)); // NOI18N
        HRlabel.setForeground(new java.awt.Color(255, 255, 255));
        HRlabel.setText("HR");
        jPanel1.add(HRlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        Dashboardlabel.setFont(new java.awt.Font("Impact", 1, 26)); // NOI18N
        Dashboardlabel.setForeground(new java.awt.Color(255, 255, 255));
        Dashboardlabel.setText("DASHBOARD");
        jPanel1.add(Dashboardlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 520));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setText("Welcome, HR Personnel");
        getContentPane().add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 600, 40));

        viewEmployeesButton.setBackground(new java.awt.Color(59, 115, 185));
        viewEmployeesButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewEmployeesButton.setForeground(new java.awt.Color(255, 255, 255));
        viewEmployeesButton.setText("View Employee List");
        viewEmployeesButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewEmployeesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmployeesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewEmployeesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 250, 40));

        logoutButton.setBackground(new java.awt.Color(59, 115, 185));
        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logout.png"))); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 150, 35));

        manageEmployeesButton.setBackground(new java.awt.Color(59, 115, 185));
        manageEmployeesButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        manageEmployeesButton.setForeground(new java.awt.Color(255, 255, 255));
        manageEmployeesButton.setText("Manage Employees");
        manageEmployeesButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageEmployeesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(manageEmployeesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 250, 40));

        leaveRequestsButton1.setBackground(new java.awt.Color(59, 115, 185));
        leaveRequestsButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        leaveRequestsButton1.setForeground(new java.awt.Color(255, 255, 255));
        leaveRequestsButton1.setText("View Leave Requests");
        leaveRequestsButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        leaveRequestsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveRequestsButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(leaveRequestsButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 250, 40));

        payslipButton1.setBackground(new java.awt.Color(59, 115, 185));
        payslipButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        payslipButton1.setForeground(new java.awt.Color(255, 255, 255));
        payslipButton1.setText("View My Own Payslip");
        payslipButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        payslipButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payslipButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(payslipButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 250, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
 // Ask the user to confirm logout
    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        // ✅ 1. Get the currently logged-in username
        String username = SessionManager.getUsername();

        // ✅ 2. Clear the session in the database (prevent multi-login)
        LoginController.clearSession(username);

        // ✅ 3. Clear session in memory (username, role, token)
        SessionManager.logout();
        
        // ✅ 4. Delete token in the database (so user won't be auto-logged in again)
        utils.RememberTokenUtil.deleteToken(username);

        // ✅ 5. Delete the saved token file (Remember Me feature)
        File tokenFile = new File("remember_token.dat");
        if (tokenFile.exists()) {
            tokenFile.delete();
        }

        // ✅ 6. Close current window (this dashboard)
        this.dispose();

        // ✅ 7. Show login screen again
        new LoginUI().setVisible(true);
    }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void viewEmployeesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmployeesButtonActionPerformed
    new EmployeeListForm().setVisible(true);
    this.dispose(); // optional: closes HRDashboard window
    }//GEN-LAST:event_viewEmployeesButtonActionPerformed

    private void manageEmployeesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeesButtonActionPerformed
    new ManageEmployeeForm().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_manageEmployeesButtonActionPerformed

    private void leaveRequestsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveRequestsButton1ActionPerformed
    new NewLeaveRequest().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_leaveRequestsButton1ActionPerformed

    private void payslipButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payslipButton1ActionPerformed
    new HRPayslipView().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_payslipButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dashboardlabel;
    private javax.swing.JLabel HRlabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton leaveRequestsButton1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton manageEmployeesButton;
    private javax.swing.JButton payslipButton1;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton viewEmployeesButton;
    // End of variables declaration//GEN-END:variables
}
