/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import employee.service.EmployeeListForm;

/**
 *
 * @author Jomax
 */
public class NewHRDashboard extends javax.swing.JFrame {

    /**
     * Creates new form NewHRDashboard
     */
    public NewHRDashboard() {
        initComponents();
        setLocationRelativeTo(null); // This centers the window
        setTitle("HR Dashboard - FinMark Payroll System");
        setSize(400, 350);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);
    }

    // ONE MAIN METHOD ONLY
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new NewHRDashboard().setVisible(true);
        });
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HRlabel = new javax.swing.JLabel();
        Dashboardlabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        viewEmployeesButton = new javax.swing.JButton();
        payslipButton = new javax.swing.JButton();
        manageEmployeesButton = new javax.swing.JButton();
        leaveRequestsButton1 = new javax.swing.JButton();
        payslipButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(555, 450));
        setPreferredSize(new java.awt.Dimension(550, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(59, 115, 185));
        jPanel1.setMinimumSize(new java.awt.Dimension(150, 1000));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 100));

        HRlabel.setFont(new java.awt.Font("Impact", 1, 40)); // NOI18N
        HRlabel.setForeground(new java.awt.Color(255, 255, 255));
        HRlabel.setText("HR");

        Dashboardlabel.setFont(new java.awt.Font("Impact", 1, 26)); // NOI18N
        Dashboardlabel.setForeground(new java.awt.Color(255, 255, 255));
        Dashboardlabel.setText("DASHBOARD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Dashboardlabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(HRlabel)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(HRlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dashboardlabel)
                .addContainerGap(893, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 520));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setText("Welcome, HR Personnel");
        getContentPane().add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 600, 40));

        viewEmployeesButton.setBackground(new java.awt.Color(59, 115, 185));
        viewEmployeesButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewEmployeesButton.setForeground(new java.awt.Color(255, 255, 255));
        viewEmployeesButton.setText("View Employee List");
        viewEmployeesButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewEmployeesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmployeesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewEmployeesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 250, 40));

        payslipButton.setBackground(new java.awt.Color(59, 115, 185));
        payslipButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        payslipButton.setForeground(new java.awt.Color(255, 255, 255));
        payslipButton.setText("Logout");
        payslipButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        payslipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payslipButtonActionPerformed(evt);
            }
        });
        getContentPane().add(payslipButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 150, 35));

        manageEmployeesButton.setBackground(new java.awt.Color(59, 115, 185));
        manageEmployeesButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        manageEmployeesButton.setForeground(new java.awt.Color(255, 255, 255));
        manageEmployeesButton.setText("Manage Employees");
        manageEmployeesButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(manageEmployeesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 250, 40));

        leaveRequestsButton1.setBackground(new java.awt.Color(59, 115, 185));
        leaveRequestsButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        leaveRequestsButton1.setForeground(new java.awt.Color(255, 255, 255));
        leaveRequestsButton1.setText("View Leave Requests");
        leaveRequestsButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(leaveRequestsButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 250, 40));

        payslipButton1.setBackground(new java.awt.Color(59, 115, 185));
        payslipButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        payslipButton1.setForeground(new java.awt.Color(255, 255, 255));
        payslipButton1.setText("View My Own Payslip");
        payslipButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(payslipButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 250, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void payslipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payslipButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payslipButtonActionPerformed

    private void viewEmployeesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmployeesButtonActionPerformed
    new EmployeeListForm().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_viewEmployeesButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dashboardlabel;
    private javax.swing.JLabel HRlabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton leaveRequestsButton1;
    private javax.swing.JButton manageEmployeesButton;
    private javax.swing.JButton payslipButton;
    private javax.swing.JButton payslipButton1;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton viewEmployeesButton;
    // End of variables declaration//GEN-END:variables
}
