/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import auth.service.NewLoginUI;
import java.io.File;
import javax.swing.JOptionPane;
import payrollmanager.view.ExportReportsView;
import payrollmanager.view.GeneratePayslips;
import payrollmanager.view.ProcessSalary;
import payrollmanager.view.ViewPayrollRecords;
import utils.JWTUtil;
import utils.SessionManager;

/**
 *
 * @author Jomax
 */
public class PayrollManagerDashboard extends javax.swing.JFrame {

    /**
     * Creates new form PayrollManagerDashboard
     */
    private javax.swing.Timer tokenMonitor;
    
    public PayrollManagerDashboard() {
        initComponents();
        setLocationRelativeTo(null); // This centers the window
        setTitle("Payroll Manager Dashboard - FinMark Payroll System");
        setSize(850, 500);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);
        startTokenMonitor(); //  Start the token watcher
    }

 //  This method checks token expiration every minute
private void startTokenMonitor() {
    tokenMonitor = new javax.swing.Timer(60000, e -> {
        String token = SessionManager.getToken();
        if (token == null || !JWTUtil.validateToken(token)) {
            JOptionPane.showMessageDialog(this, "Your session has expired. Please log in again.");
            SessionManager.logout();
            dispose(); // Close dashboard
            new NewLoginUI().setVisible(true); // Return to login
        }
    });
    tokenMonitor.start();
}   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PayrollManagerDashboardLabel = new javax.swing.JLabel();
        GeneratePayslipsButton = new javax.swing.JButton();
        ViewPayrollRecordsButton = new javax.swing.JButton();
        GeneratePayslipsButton1 = new javax.swing.JButton();
        ProcessSalaryButton = new javax.swing.JButton();
        ExportReportsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Payroll Manager Dashboard");
        setMinimumSize(new java.awt.Dimension(850, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PayrollManagerDashboardLabel.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        PayrollManagerDashboardLabel.setForeground(new java.awt.Color(255, 255, 255));
        PayrollManagerDashboardLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PayrollManagerDashboardLabel.setText("Payroll Manager Dashboard");
        jPanel1.add(PayrollManagerDashboardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 400, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 80));

        GeneratePayslipsButton.setBackground(new java.awt.Color(220, 20, 60));
        GeneratePayslipsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GeneratePayslipsButton.setForeground(new java.awt.Color(255, 255, 255));
        GeneratePayslipsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logout.png"))); // NOI18N
        GeneratePayslipsButton.setText("Logout");
        GeneratePayslipsButton.setToolTipText("Generate Payslips");
        GeneratePayslipsButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GeneratePayslipsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneratePayslipsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(GeneratePayslipsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 120, 35));

        ViewPayrollRecordsButton.setBackground(new java.awt.Color(70, 130, 180));
        ViewPayrollRecordsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewPayrollRecordsButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewPayrollRecordsButton.setText("View Payroll Records");
        ViewPayrollRecordsButton.setToolTipText("View Payroll Records");
        ViewPayrollRecordsButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ViewPayrollRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPayrollRecordsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ViewPayrollRecordsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 250, 40));

        GeneratePayslipsButton1.setBackground(new java.awt.Color(60, 179, 113));
        GeneratePayslipsButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GeneratePayslipsButton1.setForeground(new java.awt.Color(255, 255, 255));
        GeneratePayslipsButton1.setText("Generate Payslips");
        GeneratePayslipsButton1.setToolTipText("Generate Payslips");
        GeneratePayslipsButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GeneratePayslipsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneratePayslipsButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(GeneratePayslipsButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 250, 40));

        ProcessSalaryButton.setBackground(new java.awt.Color(255, 165, 0));
        ProcessSalaryButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ProcessSalaryButton.setForeground(new java.awt.Color(255, 255, 255));
        ProcessSalaryButton.setText("Process Salary");
        ProcessSalaryButton.setToolTipText("Process Salary");
        ProcessSalaryButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ProcessSalaryButton.setMaximumSize(new java.awt.Dimension(250, 40));
        ProcessSalaryButton.setMinimumSize(new java.awt.Dimension(250, 40));
        ProcessSalaryButton.setPreferredSize(new java.awt.Dimension(250, 40));
        ProcessSalaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessSalaryButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ProcessSalaryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 250, 40));

        ExportReportsButton.setBackground(new java.awt.Color(123, 104, 238));
        ExportReportsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExportReportsButton.setForeground(new java.awt.Color(255, 255, 255));
        ExportReportsButton.setText("Export Reports");
        ExportReportsButton.setToolTipText("Export Reports");
        ExportReportsButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ExportReportsButton.setMaximumSize(new java.awt.Dimension(250, 40));
        ExportReportsButton.setMinimumSize(new java.awt.Dimension(250, 40));
        ExportReportsButton.setPreferredSize(new java.awt.Dimension(250, 40));
        ExportReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportReportsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExportReportsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 250, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GeneratePayslipsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneratePayslipsButtonActionPerformed
    // Show confirmation dialog to the user
    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        // Clear stored session information (username, role, token)
        SessionManager.logout();

        // Delete the saved token file if it exists
        File tokenFile = new File("remember_token.dat");
        if (tokenFile.exists()) {
            tokenFile.delete(); // Remove saved JWT token used by 'Remember Me'
        }

        // Close the current dashboard window
        this.dispose();

        // Open the login screen again
        new NewLoginUI().setVisible(true);
    }
    }//GEN-LAST:event_GeneratePayslipsButtonActionPerformed

    private void ViewPayrollRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPayrollRecordsButtonActionPerformed
    new ViewPayrollRecords().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_ViewPayrollRecordsButtonActionPerformed

    private void GeneratePayslipsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneratePayslipsButton1ActionPerformed
    new GeneratePayslips().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_GeneratePayslipsButton1ActionPerformed

    private void ProcessSalaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessSalaryButtonActionPerformed
    new ProcessSalary().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_ProcessSalaryButtonActionPerformed

    private void ExportReportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportReportsButtonActionPerformed
    new ExportReportsView().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_ExportReportsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayrollManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayrollManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayrollManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayrollManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayrollManagerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExportReportsButton;
    private javax.swing.JButton GeneratePayslipsButton;
    private javax.swing.JButton GeneratePayslipsButton1;
    private javax.swing.JLabel PayrollManagerDashboardLabel;
    private javax.swing.JButton ProcessSalaryButton;
    private javax.swing.JButton ViewPayrollRecordsButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
