/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import auth.service.LoginController;
import teamleaderview.TeamAttendanceView;
import auth.service.LoginUI;
import java.io.File;
import javax.swing.JOptionPane;
import teamleaderview.TeamLeaderApproveLeaveForm;
import teamleaderview.TeamLeaderReportsView;
import teamleaderview.UpdateTeamInfoView;
import utils.JWTUtil;
import utils.SessionManager;

/**
 *
 * @author Jomax
 */
public class TeamLeaderDashboard extends javax.swing.JFrame {

    /**
     * Creates new form TeamLeader
     */
    private javax.swing.Timer tokenMonitor;
    
    public TeamLeaderDashboard() {
        initComponents();
        setLocationRelativeTo(null); // This centers the window
        setTitle("Team Leader Dashboard - FinMark Payroll System");
        setSize(800, 500);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);
        startTokenMonitor(); // Start the token watcher
    }
    
    // This method checks token expiration every 10 minutes
private void startTokenMonitor() {
    // Timer set to run every 10 minutes (600,000 milliseconds)
    // This code inside will execute once every 10 minutes
    tokenMonitor = new javax.swing.Timer(600000, e -> {
        String token = SessionManager.getToken();
        if (token == null || !JWTUtil.validateToken(token)) {
            JOptionPane.showMessageDialog(this, "Your session has expired. Please log in again.");
            SessionManager.logout();
            dispose(); // Close dashboard
            new LoginUI().setVisible(true); // Return to login
        }
    });
    tokenMonitor.start();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ViewTeamAttendanceButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        ApproveLeaveButton = new javax.swing.JButton();
        GenerateReportsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Team Leader Dashboard");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 128, 128));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Team Leader Dashboard");
        jLabel1.setToolTipText("Team Leader Dashboard");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 20, 400, 40);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 80));

        jButton1.setBackground(new java.awt.Color(0, 128, 128));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Update Team Info");
        jButton1.setToolTipText("Update Team Info");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setMaximumSize(new java.awt.Dimension(200, 40));
        jButton1.setMinimumSize(new java.awt.Dimension(200, 40));
        jButton1.setPreferredSize(new java.awt.Dimension(200, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 200, 40));

        ViewTeamAttendanceButton.setBackground(new java.awt.Color(0, 139, 139));
        ViewTeamAttendanceButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewTeamAttendanceButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewTeamAttendanceButton.setText("View Team Attendance");
        ViewTeamAttendanceButton.setToolTipText("View Team Attendance");
        ViewTeamAttendanceButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ViewTeamAttendanceButton.setMaximumSize(new java.awt.Dimension(200, 40));
        ViewTeamAttendanceButton.setMinimumSize(new java.awt.Dimension(200, 40));
        ViewTeamAttendanceButton.setPreferredSize(new java.awt.Dimension(200, 40));
        ViewTeamAttendanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTeamAttendanceButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ViewTeamAttendanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 200, 40));

        LogoutButton.setBackground(new java.awt.Color(139, 0, 0));
        LogoutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logout.png"))); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.setToolTipText("Logout");
        LogoutButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogoutButton.setMaximumSize(new java.awt.Dimension(200, 40));
        LogoutButton.setMinimumSize(new java.awt.Dimension(200, 40));
        LogoutButton.setPreferredSize(new java.awt.Dimension(200, 40));
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 200, 40));

        ApproveLeaveButton.setBackground(new java.awt.Color(0, 100, 0));
        ApproveLeaveButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ApproveLeaveButton.setForeground(new java.awt.Color(255, 255, 255));
        ApproveLeaveButton.setText("Approve Leave");
        ApproveLeaveButton.setToolTipText("Approve Leave");
        ApproveLeaveButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ApproveLeaveButton.setMaximumSize(new java.awt.Dimension(200, 40));
        ApproveLeaveButton.setMinimumSize(new java.awt.Dimension(200, 40));
        ApproveLeaveButton.setPreferredSize(new java.awt.Dimension(200, 40));
        ApproveLeaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApproveLeaveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ApproveLeaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 200, 40));

        GenerateReportsButton.setBackground(new java.awt.Color(255, 140, 0));
        GenerateReportsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GenerateReportsButton.setForeground(new java.awt.Color(255, 255, 255));
        GenerateReportsButton.setText("Generate Reports");
        GenerateReportsButton.setToolTipText("Generate Reports");
        GenerateReportsButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GenerateReportsButton.setMaximumSize(new java.awt.Dimension(200, 40));
        GenerateReportsButton.setMinimumSize(new java.awt.Dimension(200, 40));
        GenerateReportsButton.setPreferredSize(new java.awt.Dimension(200, 40));
        GenerateReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateReportsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(GenerateReportsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 200, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewTeamAttendanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTeamAttendanceButtonActionPerformed
    new TeamAttendanceView().setVisible(true);
    }//GEN-LAST:event_ViewTeamAttendanceButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
 // Ask the user to confirm logout
    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        // ✅ 1. Get the currently logged-in username
        String username = SessionManager.getUsername();

        // ✅ 2. Clear the session in the database (prevent multi-login)
        LoginController.clearSession(username);

        // ✅ 3. Clear session in memory (username, role, token)
        SessionManager.logout();
        
        // ✅ 4. Delete token in the database (so user won't be auto-logged in again)
        utils.RememberTokenUtil.deleteToken(username);

        // ✅ 5. Delete the saved token file (Remember Me feature)
        File tokenFile = new File("remember_token.dat");
        if (tokenFile.exists()) {
            tokenFile.delete();
        }

        // ✅ 6. Close current window (this dashboard)
        this.dispose();

        // ✅ 7. Show login screen again
        new LoginUI().setVisible(true);
    }
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void ApproveLeaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApproveLeaveButtonActionPerformed
    new TeamLeaderApproveLeaveForm().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_ApproveLeaveButtonActionPerformed

    private void GenerateReportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateReportsButtonActionPerformed
    new TeamLeaderReportsView().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_GenerateReportsButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    new UpdateTeamInfoView().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeamLeaderDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeamLeaderDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeamLeaderDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeamLeaderDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeamLeaderDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApproveLeaveButton;
    private javax.swing.JButton GenerateReportsButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton ViewTeamAttendanceButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
