/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package auth.service;

import gui.HRDashboard;
import gui.NewHRDashboard;
import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.CompoundBorder;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author Jomax
 */
public class NewLoginUI extends javax.swing.JFrame {

    
    private final String passwordPlaceholder = "Enter password";
    private boolean showingPasswordPlaceholder = true;
    
    private boolean passwordVisible = false;
    /**
     * Creates new form NewLoginUI
     */
    public NewLoginUI() {
        initComponents();
        setLocationRelativeTo(null); // This centers the window
        setTitle("Login - FinMark Payroll System");
        setSize(400, 350);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);
        
    // Add placeholders
    setPlaceholder(usernameField, "Enter username");
    setupPasswordPlaceholder();
    


    }
    
     // Username field placeholder
    private void setPlaceholder(JTextField field, String placeholder) {
        field.setForeground(Color.GRAY);
        field.setText(placeholder);

        field.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (field.getText().equals(placeholder)) {
                    field.setText("");
                    field.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (field.getText().isEmpty()) {
                    field.setForeground(Color.GRAY);
                    field.setText(placeholder);
                }
            }
        });
    }
    
     // Password field placeholder
    private void setupPasswordPlaceholder() {
        passwordField.setEchoChar((char) 0);
        passwordField.setForeground(Color.GRAY);
        passwordField.setText(passwordPlaceholder);

        passwordField.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (showingPasswordPlaceholder) {
                    passwordField.setText("");
                    passwordField.setForeground(Color.BLACK);
                    passwordField.setEchoChar('*'); // or '*'
                    showingPasswordPlaceholder = false;
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (passwordField.getPassword().length == 0) {
                    passwordField.setEchoChar((char) 0);
                    passwordField.setText(passwordPlaceholder);
                    passwordField.setForeground(Color.GRAY);
                    showingPasswordPlaceholder = true;
                }
            }
        });
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        roleComboBox = new javax.swing.JComboBox<>();
        loginButton = new javax.swing.JButton();
        companyLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        togglePasswordBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("LOGIN");
        loginLabel.setToolTipText("");
        loginLabel.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 200, 30));

        usernameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameField.setToolTipText("Enter username");
        usernameField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        usernameField.setPreferredSize(new java.awt.Dimension(220, 30));
        getContentPane().add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        roleComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HR Personnel", "Team Leader", "Payroll Manager", "Accounting Head", "Employee" }));
        roleComboBox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        roleComboBox.setPreferredSize(new java.awt.Dimension(220, 30));
        getContentPane().add(roleComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        loginButton.setBackground(new java.awt.Color(0, 123, 255));
        loginButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.setToolTipText("");
        loginButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginButton.setFocusPainted(false);
        loginButton.setPreferredSize(new java.awt.Dimension(220, 30));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        companyLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        companyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        companyLabel.setText("© 2025 FinMark Payroll System");
        companyLabel.setPreferredSize(new java.awt.Dimension(240, 20));
        getContentPane().add(companyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        passwordField.setText("jPasswordField1");
        passwordField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        passwordField.setPreferredSize(new java.awt.Dimension(220, 30));
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        togglePasswordBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        togglePasswordBtn.setPreferredSize(new java.awt.Dimension(30, 30));
        togglePasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglePasswordBtnActionPerformed(evt);
            }
        });
        getContentPane().add(togglePasswordBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void togglePasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglePasswordBtnActionPerformed
    if (!showingPasswordPlaceholder) {
        if (passwordVisible) {
            passwordField.setEchoChar('*');
            togglePasswordBtn.setIcon(new ImageIcon(getClass().getResource("/resources/eye-off.png")));
            passwordVisible = false;
        } else {
            passwordField.setEchoChar((char) 0);
            togglePasswordBtn.setIcon(new ImageIcon(getClass().getResource("/resources/eye.png")));
            passwordVisible = true;
        }
    }
    }//GEN-LAST:event_togglePasswordBtnActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
String username = usernameField.getText();
String password = new String(passwordField.getPassword());
String role = roleComboBox.getSelectedItem().toString();

if (LoginController.login(username, password, role)) {
    JOptionPane.showMessageDialog(this, "Login successful!");
    this.dispose();
    new NewHRDashboard().setVisible(true); // or role-based dashboard
} else {
    JOptionPane.showMessageDialog(this, "Invalid credentials");
}
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewLoginUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel companyLabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JComboBox<String> roleComboBox;
    private javax.swing.JButton togglePasswordBtn;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
