/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package payrollmanager.view;

import gui.AccountingHeadDashboard;
import gui.PayrollManagerDashboard;

/**
 *
 * @author Jomax
 */
public class ExportReportsView extends javax.swing.JFrame {

    /**
     * Creates new form ExportReportsView
     */
    public ExportReportsView() {
        initComponents();
        setTitle("Export Reports View - FinMark Payroll System");
        setSize(850, 600);
        setLocationRelativeTo(null); // This centers the window
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ExportReportsLabel = new javax.swing.JLabel();
        ReportTypeLabel = new javax.swing.JLabel();
        ExportComboComboBox = new javax.swing.JComboBox<>();
        FileFormatLabel = new javax.swing.JLabel();
        FormatCombo = new javax.swing.JComboBox<>();
        DirectoryLabel = new javax.swing.JLabel();
        PathField = new javax.swing.JTextField();
        BrowseButton = new javax.swing.JButton();
        ExportButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Export Reports View");
        setMinimumSize(new java.awt.Dimension(850, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setMinimumSize(new java.awt.Dimension(850, 80));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExportReportsLabel.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        ExportReportsLabel.setForeground(new java.awt.Color(255, 255, 255));
        ExportReportsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExportReportsLabel.setText("Export Reports");
        ExportReportsLabel.setToolTipText("Export Reports");
        ExportReportsLabel.setMaximumSize(new java.awt.Dimension(400, 40));
        ExportReportsLabel.setMinimumSize(new java.awt.Dimension(400, 40));
        ExportReportsLabel.setPreferredSize(new java.awt.Dimension(400, 40));
        jPanel1.add(ExportReportsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 400, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 80));

        ReportTypeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ReportTypeLabel.setText("Report Type:");
        ReportTypeLabel.setToolTipText("Report Type");
        ReportTypeLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        ReportTypeLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        ReportTypeLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(ReportTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 150, 30));

        ExportComboComboBox.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ExportComboComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Attendance Report", "Payroll Summary", "Payslip Batch", "Leave Requests Report", "Government Deductions", "Overtime Logs", "Monthly Salary Report" }));
        ExportComboComboBox.setToolTipText("Select Report Type");
        ExportComboComboBox.setMinimumSize(new java.awt.Dimension(200, 30));
        ExportComboComboBox.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(ExportComboComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 200, 30));

        FileFormatLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FileFormatLabel.setText("File Format:");
        FileFormatLabel.setToolTipText("File Format");
        FileFormatLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        FileFormatLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        FileFormatLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(FileFormatLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 150, 30));

        FormatCombo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        FormatCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PDF", "Excel", "CSV" }));
        FormatCombo.setMinimumSize(new java.awt.Dimension(200, 30));
        FormatCombo.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(FormatCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 200, 30));

        DirectoryLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DirectoryLabel.setText("Save to:");
        DirectoryLabel.setToolTipText("Directory");
        DirectoryLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        DirectoryLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        DirectoryLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(DirectoryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 150, 30));

        PathField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        PathField.setToolTipText("Path Field");
        PathField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        PathField.setMinimumSize(new java.awt.Dimension(300, 30));
        PathField.setPreferredSize(new java.awt.Dimension(300, 30));
        getContentPane().add(PathField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 300, 30));

        BrowseButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        BrowseButton.setText("Browse");
        BrowseButton.setToolTipText("Browse");
        BrowseButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(BrowseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 80, 30));

        ExportButton.setBackground(new java.awt.Color(0, 128, 0));
        ExportButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        ExportButton.setForeground(new java.awt.Color(255, 255, 255));
        ExportButton.setText("Export");
        ExportButton.setToolTipText("Export");
        ExportButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ExportButton.setMaximumSize(new java.awt.Dimension(100, 35));
        ExportButton.setMinimumSize(new java.awt.Dimension(100, 35));
        ExportButton.setPreferredSize(new java.awt.Dimension(100, 35));
        getContentPane().add(ExportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 100, 35));

        CancelButton.setBackground(new java.awt.Color(128, 128, 128));
        CancelButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(255, 255, 255));
        CancelButton.setText("Cancel");
        CancelButton.setToolTipText("Cancel");
        CancelButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CancelButton.setMaximumSize(new java.awt.Dimension(100, 35));
        CancelButton.setMinimumSize(new java.awt.Dimension(100, 35));
        CancelButton.setPreferredSize(new java.awt.Dimension(100, 35));
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 100, 35));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
    this.dispose();
    new PayrollManagerDashboard().setVisible(true); // go back to Payroll Manager Dashboard page
    }//GEN-LAST:event_CancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExportReportsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExportReportsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExportReportsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExportReportsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExportReportsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BrowseButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel DirectoryLabel;
    private javax.swing.JButton ExportButton;
    private javax.swing.JComboBox<String> ExportComboComboBox;
    private javax.swing.JLabel ExportReportsLabel;
    private javax.swing.JLabel FileFormatLabel;
    private javax.swing.JComboBox<String> FormatCombo;
    private javax.swing.JTextField PathField;
    private javax.swing.JLabel ReportTypeLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
